import { IDecoUnit } from "./types.d.ts";

const decos: IDecoUnit[] = [
  {
    name: "Deco X90",
    packs: 2,
    price: 570 /* in USD */,
    speed: [4804, 1201, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 7000 /* sq.ft */,
    features: {
      antennas: 4 + 2 /* Wi-Fi Internal Antennas */,
      bands: 3 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 8 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco X5700",
    packs: 2,
    price: 330 /* in USD */,
    speed: [3843, 1201, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 6000 /* sq.ft */,
    features: {
      antennas: 4 + 2 /* Wi-Fi Internal Antennas */,
      bands: 3 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 8 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco X68",
    packs: 3,
    price: 490 /* in USD */,
    speed: [1802, 1201, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 8100 /* sq.ft */,
    features: {
      antennas: 5 /* Wi-Fi Internal Antennas */,
      bands: 3 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 7 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco X60",
    packs: 3,
    price: 360 /* in USD */,
    speed: [2402, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 7000 /* sq.ft */,
    features: {
      antennas: 4 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 6 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco X55",
    packs: 3,
    price: 300 /* in USD */,
    speed: [2402, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 6500 /* sq.ft */,
    features: {
      antennas: 2 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 4 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco M9+",
    packs: 3,
    price: 330 /* in USD */,
    speed: [867, 867, 400] /* 5Ghz, 2.4Ghz */,
    coverage: 6500 /* sq.ft */,
    features: {
      antennas: 8 /* Wi-Fi Internal Antennas */,
      bands: 3 /* Wi-Fi bands */,
      wifi: 5 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 0 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 0 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco X20",
    packs: 3,
    price: 270 /* in USD */,
    speed: [1201, 574] /* 5Ghz, 2.4Ghz */,
    coverage: 5800 /* sq.ft */,
    features: {
      antennas: 2 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 6 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 1 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 4 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco M4",
    packs: 3,
    price: 153 /* in USD */,
    speed: [867, 300] /* 5Ghz, 2.4Ghz */,
    coverage: 5500 /* sq.ft */,
    features: {
      antennas: 2 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 5 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 0 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 0 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco S4",
    packs: 3,
    price: 140 /* in USD */,
    speed: [867, 300] /* 5Ghz, 2.4Ghz */,
    coverage: 5500 /* sq.ft */,
    features: {
      antennas: 2 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 5 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 0 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 0 /* Parallels Streams count */,
    },
  },
  {
    name: "Deco E4",
    packs: 3,
    price: 123 /* in USD */,
    speed: [867, 300] /* 5Ghz, 2.4Ghz */,
    coverage: 4000 /* sq.ft */,
    features: {
      antennas: 2 /* Wi-Fi Internal Antennas */,
      bands: 2 /* Wi-Fi bands */,
      wifi: 5 /* Wi-Fi version */,
      wifi_6e: 0 /* Wi-Fi 6 Extended */,
      ofdma: 0 /* Wi-Fi 6 technology that reduces power consumption */,
      streams: 0 /* Parallels Streams count */,
    },
  },
];

export default decos;
